steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/proj-artifacts/train',
    '-f',
    './dockerfiles/train.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/proj-artifacts/train'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image 2'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/proj-artifacts/api',
    '-f',
    './dockerfiles/api.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image 2'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/proj-artifacts/api'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
