name: Unit Tests

on:
  push:
    branches:
      - main
      - actions-develop
  pull_request:
    branches:
      - main
      - actions-develop
    branches-ignore:
      - docs/checklist

jobs:
  test:
    environment: gcp
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements.txt
          pip install -r requirements_api.txt
          pip install -r requirements_frontend.txt
          pip install -r requirements_test.txt
          pip install -e .
          pip list

      - name: Run tests & coverage
        env:
          BUCKET_NAME: ${{ vars.BUCKET_NAME }}
        run: |
          coverage run -m pytest tests/
          coverage report -m -i
